name: Chess Discord Notification

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check-games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python chess_notifier.py
