name: Chess Discord Notification

on:
  workflow_dispatch:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  check-games:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run chess notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python chess_notifier.py

      - name: Commit updated notifier state
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add seen_games.json seen_matches.json seen_registered_matches.json

          if ! git diff --cached --quiet; then
            git commit -m "Update notification history"
            git push
          else
            echo "No changes to notification history"
          fi
